=== MISP/misp-warninglists/schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "title": "Validator for misp-warninglists",
  "id": "https://www.github.com/MISP/misp-warninglists/schema.json",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "description": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "version": {
      "type": "integer"
    },
    "list": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    },
    "type": {
      "type": "string",
      "enum": [
        "string",
        "substring",
        "hostname",
        "cidr",
        "regex"
      ]
    },
    "matching_attributes": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    }
  },
  "required": [
    "list",
    "description",
    "version",
    "name",
    "type"
  ]
}

=== MISP/misp-warninglists/lists/googlebot/list.json
{
  "description": "Google Bot IP address ranges (https://developers.google.com/search/apis/ipranges/googlebot.json)",
  "list": [
    "192.178.4.0/24",
    "192.178.5.0/27",
    "192.178.6.0/23",
    "2001:4860:4801:10::/60",
    "2001:4860:4801:20::/59",
    "2001:4860:4801:2::/64",
    "2001:4860:4801:40::/63",
    "2001:4860:4801:42::/64",
    "2001:4860:4801:44::/62",
    "2001:4860:4801:48::/62",
    "2001:4860:4801:4c::/63",
    "2001:4860:4801:4e::/64",
    "2001:4860:4801:50::/61",
    "2001:4860:4801:58::/63",
    "2001:4860:4801:60::/60",
    "2001:4860:4801:70::/61",
    "2001:4860:4801:78::/62",
    "2001:4860:4801:7c::/63",
    "2001:4860:4801:80::/61",
    "2001:4860:4801:88::/64",
    "2001:4860:4801:90::/61",
    "2001:4860:4801:a0::/61",
    "2001:4860:4801:a8::/62",
    "2001:4860:4801:ac::/63",
    "2001:4860:4801:ae::/64",
    "2001:4860:4801:b0::/62",
    "2001:4860:4801:b4::/63",
    "2001:4860:4801:b6::/64",
    "2001:4860:4801:c::/64",
    "2001:4860:4801:f::/64",
    "34.100.182.96/28",
    "34.101.50.144/28",
    "34.118.254.0/28",
    "34.118.66.0/28",
    "34.126.178.96/28",
    "34.146.150.144/28",
    "34.147.110.144/28",
    "34.151.74.144/28",
    "34.152.50.64/28",
    "34.154.114.144/28",
    "34.155.98.32/28",
    "34.165.18.176/28",
    "34.175.160.64/28",
    "34.176.130.16/28",
    "34.22.85.0/27",
    "34.64.82.64/28",
    "34.65.242.112/28",
    "34.80.50.80/28",
    "34.88.194.0/28",
    "34.89.10.80/28",
    "34.89.198.80/28",
    "34.96.162.48/28",
    "35.247.243.240/28",
    "66.249.64.0/23",
    "66.249.66.0/24",
    "66.249.67.0/26",
    "66.249.67.64/27",
    "66.249.68.0/25",
    "66.249.68.128/26",
    "66.249.68.192/27",
    "66.249.69.0/24",
    "66.249.70.0/23",
    "66.249.72.0/22",
    "66.249.76.0/23",
    "66.249.78.0/25",
    "66.249.78.128/26",
    "66.249.79.0/26",
    "66.249.79.128/25",
    "66.249.79.64/27"
  ],
  "matching_attributes": [
    "ip-src",
    "ip-dst",
    "domain|ip",
    "ip-src|port",
    "ip-dst|port"
  ],
  "name": "List of known Googlebot IP ranges (https://developers.google.com/search/apis/ipranges/googlebot.json)",
  "type": "cidr",
  "version": 20260520
}

=== MISP/misp-warninglists/lists/internet-census-nt-scanning/list.json
{
  "description": "List containing IP's associated with the Internet census scanners. This scanner CIDR range is extracted from CIRCL Network Telescope analysis on 2026/06/01",
  "list": [
    "109.105.209.10/32",
    "109.105.209.12/30",
    "109.105.209.17/32",
    "109.105.209.18/31",
    "109.105.209.2/31",
    "109.105.209.20/32",
    "109.105.209.22/31",
    "109.105.209.24/31",
    "109.105.209.27/32",
    "109.105.209.28/31",
    "109.105.209.30/32",
    "109.105.209.32/30",
    "109.105.209.37/32",
    "109.105.209.38/31",
    "109.105.209.4/31",
    "109.105.209.40/32",
    "109.105.209.42/31",
    "109.105.209.44/31",
    "109.105.209.47/32",
    "109.105.209.48/31",
    "109.105.209.50/32",
    "109.105.209.7/32",
    "109.105.209.8/31",
    "109.105.210.100/32",
    "109.105.210.102/31",
    "109.105.210.104/31",
    "109.105.210.52/30",
    "109.105.210.57/32",
    "109.105.210.58/31",
    "109.105.210.60/32",
    "109.105.210.62/31",
    "109.105.210.64/31",
    "109.105.210.67/32",
    "109.105.210.68/31",
    "109.105.210.70/32",
    "109.105.210.72/30",
    "109.105.210.77/32",
    "109.105.210.78/31",
    "109.105.210.80/32",
    "109.105.210.82/31",
    "109.105.210.84/31",
    "109.105.210.87/32",
    "109.105.210.88/31",
    "109.105.210.90/32",
    "109.105.210.92/30",
    "109.105.210.97/32",
    "109.105.210.98/31",
    "109.105.211.16/31",
    "109.105.211.2/31",
    "109.105.211.4/30",
    "109.105.211.8/29",
    "185.180.141.10/32",
    "185.180.141.12/30",
    "185.180.141.17/32",
    "185.180.141.2/31",
    "185.180.141.21/32",
    "185.180.141.22/32",
    "185.180.141.32/30",
    "185.180.141.37/32",
    "185.180.141.38/31",
    "185.180.141.4/31",
    "185.180.141.40/32",
    "185.180.141.42/31",
    "185.180.141.44/31",
    "185.180.141.47/32",
    "185.180.141.48/31",
    "185.180.141.50/32",
    "185.180.141.52/30",
    "185.180.141.57/32",
    "185.180.141.58/31",
    "185.180.141.60/32",
    "185.180.141.67/32",
    "185.180.141.68/31",
    "185.180.141.7/32",
    "185.180.141.70/32",
    "185.180.141.8/31",
    "185.226.196.10/32",
    "185.226.196.12/30",
    "185.226.196.17/32",
    "185.226.196.18/31",
    "185.226.196.2/32",
    "185.226.196.20/32",
    "185.226.196.22/31",
    "185.226.196.24/31",
    "185.226.196.27/32",
    "185.226.196.28/31",
    "185.226.196.30/32",
    "185.226.196.4/31",
    "185.226.196.7/32",
    "185.226.196.8/31",
    "185.226.197.10/32",
    "185.226.197.12/30",
    "185.226.197.17/32",
    "185.226.197.2/31",
    "185.226.197.22/32",
    "185.226.197.27/32",
    "185.226.197.28/31",
    "185.226.197.30/32",
    "185.226.197.32/30",
    "185.226.197.37/32",
    "185.226.197.38/31",
    "185.226.197.4/31",
    "185.226.197.40/32",
    "185.226.197.42/31",
    "185.226.197.44/31",
    "185.226.197.47/32",
    "185.226.197.48/31",
    "185.226.197.50/32",
    "185.226.197.52/30",
    "185.226.197.57/32",
    "185.226.197.58/31",
    "185.226.197.60/32",
    "185.226.197.62/31",
    "185.226.197.64/31",
    "185.226.197.67/32",
    "185.226.197.68/31",
    "185.226.197.7/32",
    "185.226.197.70/32",
    "185.226.197.72/30",
    "185.226.197.8/31",
    "45.156.128.10/31",
    "45.156.128.101/32",
    "45.156.128.102/31",
    "45.156.128.104/32",
    "45.156.128.106/31",
    "45.156.128.108/31",
    "45.156.128.111/32",
    "45.156.128.112/31",
    "45.156.128.114/32",
    "45.156.128.116/30",
    "45.156.128.121/32",
    "45.156.128.122/31",
    "45.156.128.124/32",
    "45.156.128.126/31",
    "45.156.128.128/30",
    "45.156.128.13/32",
    "45.156.128.14/31",
    "45.156.128.148/30",
    "45.156.128.152/29",
    "45.156.128.164/30",
    "45.156.128.168/29",
    "45.156.128.176/30",
    "45.156.128.37/32",
    "45.156.128.39/32",
    "45.156.128.41/32",
    "45.156.128.43/32",
    "45.156.128.45/32",
    "45.156.128.47/32",
    "45.156.128.49/32",
    "45.156.128.5/32",
    "45.156.128.51/32",
    "45.156.128.52/31",
    "45.156.128.54/32",
    "45.156.128.56/30",
    "45.156.128.6/31",
    "45.156.128.61/32",
    "45.156.128.62/31",
    "45.156.128.64/32",
    "45.156.128.66/31",
    "45.156.128.68/31",
    "45.156.128.71/32",
    "45.156.128.72/31",
    "45.156.128.74/32",
    "45.156.128.76/30",
    "45.156.128.8/32",
    "45.156.128.81/32",
    "45.156.128.82/31",
    "45.156.128.84/32",
    "45.156.128.86/31",
    "45.156.128.88/31",
    "45.156.128.91/32",
    "45.156.128.92/31",
    "45.156.128.94/32",
    "45.156.128.96/30",
    "45.156.129.100/30",
    "45.156.129.105/32",
    "45.156.129.106/31",
    "45.156.129.108/32",
    "45.156.129.110/31",
    "45.156.129.112/31",
    "45.156.129.115/32",
    "45.156.129.116/31",
    "45.156.129.118/32",
    "45.156.129.120/30",
    "45.156.129.125/32",
    "45.156.129.126/31",
    "45.156.129.128/32",
    "45.156.129.130/31",
    "45.156.129.132/30",
    "45.156.129.136/30",
    "45.156.129.152/29",
    "45.156.129.160/28",
    "45.156.129.176/30",
    "45.156.129.185/32",
    "45.156.129.186/31",
    "45.156.129.188/30",
    "45.156.129.193/32",
    "45.156.129.194/31",
    "45.156.129.197/32",
    "45.156.129.198/31",
    "45.156.129.42/32",
    "45.156.129.44/32",
    "45.156.129.46/32",
    "45.156.129.48/32",
    "45.156.129.51/32",
    "45.156.129.52/32",
    "45.156.129.54/32",
    "45.156.129.56/31",
    "45.156.129.60/30",
    "45.156.129.65/32",
    "45.156.129.66/31",
    "45.156.129.68/32",
    "45.156.129.70/31",
    "45.156.129.72/31",
    "45.156.129.75/32",
    "45.156.129.76/31",
    "45.156.129.78/32",
    "45.156.129.80/30",
    "45.156.129.85/32",
    "45.156.129.86/31",
    "45.156.129.88/32",
    "45.156.129.90/31",
    "45.156.129.92/31",
    "45.156.129.95/32",
    "45.156.129.96/31",
    "45.156.129.98/32",
    "45.156.130.10/31",
    "45.156.130.12/31",
    "45.156.130.15/32",
    "45.156.130.16/31",
    "45.156.130.18/32",
    "45.156.130.2/32",
    "45.156.130.20/30",
    "45.156.130.25/32",
    "45.156.130.26/31",
    "45.156.130.28/32",
    "45.156.130.30/31",
    "45.156.130.32/31",
    "45.156.130.35/32",
    "45.156.130.36/31",
    "45.156.130.38/32",
    "45.156.130.4/32",
    "45.156.130.40/30",
    "45.156.130.45/32",
    "45.156.130.46/31",
    "45.156.130.6/32",
    "45.156.130.8/32",
    "45.156.131.10/32",
    "45.156.131.12/30",
    "45.156.131.17/32",
    "45.156.131.18/31",
    "45.156.131.2/31",
    "45.156.131.20/32",
    "45.156.131.22/31",
    "45.156.131.24/31",
    "45.156.131.27/32",
    "45.156.131.28/31",
    "45.156.131.30/32",
    "45.156.131.4/31",
    "45.156.131.7/32",
    "45.156.131.8/31"
  ],
  "matching_attributes": [
    "ip-src",
    "ip-dst",
    "domain|ip",
    "ip-dst|port",
    "ip-src|port"
  ],
  "name": "Internet census IP Ranges Used for Scanning",
  "type": "cidr",
  "version": 26060109
}

=== MISP/misp-warninglists/lists/tenable-cloud-ipv6/list.json
{
  "description": "Tenable IPv6 Cloud Sensor addresses used for scanning Internet-facing infrastructure",
  "list": [
    "2406:da14:e76:5b00::/56",
    "2406:da17:524:dd00::/56",
    "2406:da18:844:7100::/56",
    "2406:da1a:5b2:8500::/56",
    "2406:da1c:20f:2f00::/56",
    "2600:1f11:622:3000::/56",
    "2600:1f14:141:7b00::/56",
    "2600:1f16:8ca:e900::/56",
    "2600:1f18:614c:8000::/56",
    "2600:1f1e:9a:ba00::/56",
    "2606:4700:7::1a/128",
    "2606:4700:7::a29f:8153/128",
    "2606:4700:7::a29f:8253/128",
    "2a05:d014:532:b00::/56",
    "2a05:d018:f53:4100::/56",
    "2a05:d01c:da5:e800::/56",
    "2a06:98c1:58::1a/128"
  ],
  "matching_attributes": [
    "ip-src",
    "ip-dst",
    "domain|ip",
    "ip-src|port",
    "ip-dst|port"
  ],
  "name": "List of known Tenable Cloud Sensors IPv6",
  "type": "cidr",
  "version": 20260611
}

=== MISP/misp-warninglists/lists/shodan-nt-scanning/list.json
{
  "description": "List containing IP's associated with the Shodan scanners. This scanner CIDR range is extracted from CIRCL Network Telescope analysis on 2026/06/01",
  "list": [
    "185.142.236.34/31",
    "185.142.236.36/32",
    "185.142.236.41/32",
    "185.142.239.16/32",
    "66.240.192.138/32",
    "66.240.205.34/32",
    "66.240.219.146/32",
    "66.240.236.119/32",
    "71.6.135.131/32",
    "71.6.146.130/32",
    "71.6.146.185/32",
    "71.6.146.186/32",
    "71.6.147.254/32",
    "71.6.158.166/32",
    "71.6.165.200/32",
    "71.6.167.142/32",
    "71.6.199.23/32",
    "80.82.77.139/32",
    "80.82.77.33/32",
    "86.54.31.32/32",
    "86.54.31.34/32",
    "86.54.31.36/32",
    "86.54.31.38/32",
    "86.54.31.40/32",
    "86.54.31.42/32",
    "86.54.31.44/32",
    "89.248.167.131/32",
    "89.248.172.16/32",
    "93.174.95.106/32",
    "94.102.49.193/32"
  ],
  "matching_attributes": [
    "ip-src",
    "ip-dst",
    "domain|ip",
    "ip-dst|port",
    "ip-src|port"
  ],
  "name": "Shodan IP Ranges Used for Scanning",
  "type": "cidr",
  "version": 26060109
}

=== MISP/misp-warninglists/lists/common-ioc-false-positive/list.json
{
  "description": "Event contains one or more entries with common false-positives",
  "list": [
    "01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b",
    "048846ed8ed185a26394adeb3f63274d1029bbd59cffa8e73a4ef8b19456de1d",
    "06f7826c2862d184a49e3672c0aa6097b11e7771a4bf613ec37941236c1a8e20",
    "07c4c7ae2c4c7cb3ccd2ba9cd70a94382395ca8e2b0312c1631d09d790b6db33",
    "0f343b0931126a20f133d67c2b018a3b",
    "10400c6faf166902b52fb97042f1e0eb",
    "125da188e26bd119ce8cad7eeb1fc2dfa147ad47",
    "16e8e953c65d610c3bfc595240f3f5b7",
    "183d0929423da2aa83441ee625de92b213f33948",
    "1ceaf73df40e531df3bfb26b4fb7cd95fb7bff1d",
    "200ceb26807d6bf99fd6f4f0d1ca54d4",
    "231a802e6ff1fae42f2b12561fff2767d473210b",
    "2daeaa8b5f19f0bc209d976c02bd6acb51b00b0a",
    "325472601571f31e1bf00674c368d335",
    "4194d1706ed1f408d5e02d672777019f4d5385c766a8c6ca8acba3167d36a7b9",
    "41f958d2d3e9ed4504b6a8863fd72b49",
    "4a15a6777284035dfd8df4ecf496b4f0557a9cc4ffaaf5887659031e843865e1",
    "4b298058e1d5fd3f2fa20ead21773912a5dc38da3c0da0bbc7de1adfb6011f1c",
    "4b6c7f3146f86136507497232d2f04a0",
    "4dde54cfc600dbd9a610645d197a632e064115ffaa3a1b595c3a23036e501678",
    "5ba93c9db0cff93f52b521d7420e43f6eda2784f",
    "5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
    "605db3fdbaff4ba13729371ad0c4fbab3889378e",
    "60cacbf3d72e1e7834203da608037b1bf83b40e8",
    "620f0b67a91f7f74151bc5be745b7110",
    "68b329da9893e34099c7d8ad5cb9c940",
    "6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d",
    "72c2dbbb1fe642073002b30987fcd68921a6b140",
    "7eb70257593da06f682a3ddda54a9d260d4fc514f645237f5ca74b08f8da61a6",
    "8094af5ee310714caebccaeee7769ffb08048503ba478b879edfef5f1a24fefe",
    "81051bcc2cf1bedf378224b0a93e2877",
    "86f1895ae8c5e8b17d99ece768a70732",
    "8a798890fe93817163b10b5f7bd2ca4d25d84c52739a645a889c173eee7d9d3d",
    "93b885adfe0da089cdf634904fd59f71",
    "995c770caeb45f7f0c1bc3affc60f11d8c40e16027df2cf711f95824f3534b6f",
    "a11a2f0cfe6d0b4c50945989db6360cd",
    "a6105c0a611b41b08f1209506350279e",
    "ad7facb2586fc6e966c004d7d1d16b024f5805ff7cb47c7a85dabd8b48892ca7",
    "adc83b19e793491b1c6ea0fd8b46cd9f32e592fc",
    "b1442e85b03bdcaf66dc58c7abb98745dd2687d86350be9a298a1d9382ac849b",
    "b3aca92c793ee0e9b1a9b0a5f5fc044e05140df3",
    "b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c",
    "b6f9aa44c5f0565b5deb761b1926e9b6",
    "ba8ab5a0280b953aa97435ff8946cbcbb2755a27",
    "c4232ddd4d37b9c0884bd44d8476578c54d7f98d58945728e425736a6a07e102",
    "c5e389341a0b19b6f045823abffc9814",
    "c82cee5f957ad01068f487eecd430a1389e0d922",
    "c929701c67a05f90827563eedccf5eba8e65b2da970189a0371f28cd896708b8",
    "c99a74c555371a433d121f551d6c6398",
    "d378bffb70923139d6a4f546864aa61c",
    "d3b07384d113edec49eaa6238ad5ff00",
    "d41d8cd98f00b204e9800998ecf8427e",
    "d5502a1d00787d68f548ddeebbde1eca5e2b38ca",
    "d583c3aa489ed954df3be71e71deae3a9895857e",
    "d991c16949bd5e85e768385440e18d493ce3aa46",
    "da39a3ee5e6b4b0d3255bfef95601890afd80709",
    "deabe082bc0f0f503292e537b2675c7c93dca40f",
    "df4e26a04a444901b95afef44e4a96cfae34690fff2ad2c66389c70079cdff2b",
    "e24133dd836d99182a6227dcf6613d08",
    "e2516fcd1573e70334c8f50bee5241cdfdf48a00",
    "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "e5a00aa9991ac8a5ee3109844d84a55583bd20572ad3ffcd42792f3c36b183ad",
    "e617348b8947f28e2a280dd93c75a6ad",
    "f00aa51c2ed8b2f656318fdc01ee1cf5441011a4",
    "f1d2d2f924e986ac86fdf7b36c94bcdf32beec15",
    "f6d380b256b0e66ef347adc78195fd0f228b3e33",
    "fa8715078d45101200a6e2bf7321aa04",
    "fb360f9c09ac8c5edb2f18be5de4e80ea4c430d0",
    "fc4623b113a1f603c0d9ad5f83130bd6de1c62b973be9892305132389c8588de"
  ],
  "matching_attributes": [
    "md5",
    "sha1",
    "sha224",
    "sha256",
    "sha512",
    "filename|md5",
    "filename|sha1",
    "filename|sha224",
    "filename|sha256",
    "filename|sha512"
  ],
  "name": "List of known hashes with common false-positives (based on Florian Roth input list)",
  "type": "string",
  "version": 2
}

=== MISP/misp-warninglists/lists/Censys_Scanning/list.json
{
  "name": "Censys IP Ranges Used for Scanning",
  "type": "cidr",
  "version": 1,
  "description": "List containing IP's accocaited with Censys scanning [https://support.censys.io/hc/en-us/articles/360043177092-Opt-Out-of-Data-Collection#Can_I_opt_out_of_Censys_data_collection?]",
  "matching_attributes": [
    "ip-src",
    "ip-dst",
    "domain|ip",
    "ip-dst|port",
    "ip-src|port"
  ],
  "list": [
    "162.142.125.0/24",
    "167.94.138.0/24",
    "167.94.145.0/24",
    "167.94.146.0/24",
    "167.248.133.0/24",
    "2602:80d:1000:b0cc:e::/80",
	"2620:96:e000:b0cc:e::/80"
  ]
}

=== MISP/misp-warninglists/lists/microsoft-office365/list.json
{
  "description": "Office 365 URLs and IP address ranges",
  "list": [
    "aadrm.com",
    "account.activedirectory.windowsazure.com",
    "account.live.com",
    "accounts.accesscontrol.windows.net",
    "acompli.net",
    "activation.sls.microsoft.com",
    "activity.windows.com",
    "adl.windows.com",
    "admin.microsoft.com",
    "admin.onedrive.com",
    "adminwebservice.microsoftonline.com",
    "ajax.aspnetcdn.com",
    "aka.ms",
    "amp.azure.net",
    "api.passwordreset.microsoftonline.com",
    "apis.live.net",
    "appex-rf.msn.com",
    "appex.bing.com",
    "appsforoffice.microsoft.com",
    "aria.microsoft.com",
    "assets-yammer.com",
    "assets.onestore.ms",
    "auth.gfx.ms",
    "auth.microsoft.com",
    "autologon.microsoftazuread-sso.com",
    "azure-apim.net",
    "azurerms.com",
    "becws.microsoftonline.com",
    "c.bing.com",
    "c.bing.net",
    "c.live.com",
    "c1.microsoft.com",
    "cacerts.digicert.com",
    "ccs.login.microsoftonline.com",
    "cdn.odc.officeapps.live.com",
    "cdn.onenote.net",
    "cdn.uci.officeapps.live.com",
    "cert.int-x3.letsencrypt.org",
    "clientconfig.microsoftonline-p.net",
    "cloud.microsoft",
    "companymanager.microsoftonline.com",
    "compliance.microsoft.com",
    "cortana.ai",
    "crl.globalsign.com",
    "crl.globalsign.net",
    "crl.identrust.com",
    "crl.microsoft.com",
    "crl3.digicert.com",
    "crl4.digicert.com",
    "dc.services.visualstudio.com",
    "defender.microsoft.com",
    "device.login.microsoftonline.com",
    "dgps.support.microsoft.com",
    "docs.microsoft.com",
    "ecn.dev.virtualearth.net",
    "enterpriseregistration.windows.net",
    "entrust.net",
    "eus-www.sway-cdn.com",
    "eus-www.sway-extensions.com",
    "events.data.microsoft.com",
    "flow.microsoft.com",
    "g.live.com",
    "geotrust.com",
    "go.microsoft.com",
    "graph.microsoft.com",
    "graph.windows.net",
    "hip.live.com",
    "informationprotection.azure.com",
    "informationprotection.hosting.portal.azure.net",
    "isrg.trustid.ocsp.identrust.com",
    "join.secure.skypeassets.com",
    "keydelivery.mediaservices.windows.net",
    "login-us.microsoftonline.com",
    "login.live.com",
    "login.microsoft.com",
    "login.microsoftonline-p.com",
    "login.microsoftonline.com",
    "login.windows-ppe.net",
    "login.windows.net",
    "logincert.microsoftonline.com",
    "loginex.microsoftonline.com",
    "lync.com",
    "mail.protection.outlook.com",
    "mem.gfx.ms",
    "microsoft.com",
    "microsoftonline-p.com",
    "microsoftonline.com",
    "microsoftusercontent.com",
    "mlccdnprod.azureedge.net",
    "msauth.net",
    "msauthimages.net",
    "mscrl.microsoft.com",
    "msdn.microsoft.com",
    "msecnd.net",
    "msftauth.net",
    "msftauthimages.net",
    "msftidentity.com",
    "msidentity.com",
    "msocdn.com",
    "mx.microsoft",
    "nexus.microsoftonline-p.com",
    "o15.officeredir.microsoft.com",
    "o365weve.com",
    "ocos-office365-s2s.msedge.net",
    "ocsp.digicert.com",
    "ocsp.globalsign.com",
    "ocsp.msocsp.com",
    "ocsp2.globalsign.com",
    "ocspx.digicert.com",
    "office.com",
    "office.live.com",
    "office.net",
    "office15client.microsoft.com",
    "office365.com",
    "officeapps.live.com",
    "officecdn.microsoft.com",
    "officeclient.microsoft.com",
    "officepreviewredir.microsoft.com",
    "officeredir.microsoft.com",
    "officespeech.platform.bing.com",
    "omniroot.com",
    "oneclient.sfx.ms",
    "onenote.com",
    "oneocsp.microsoft.com",
    "online.office.com",
    "onmicrosoft.com",
    "otelrules.azureedge.net",
    "outlook.cloud.microsoft",
    "outlook.com",
    "outlook.office.com",
    "outlook.office365.com",
    "outlookmobile.com",
    "partnerservices.getmicrosoftkey.com",
    "passwordreset.microsoftonline.com",
    "phonefactor.net",
    "platform.linkedin.com",
    "portal.cloudappsecurity.com",
    "powerapps.com",
    "powerautomate.com",
    "prod.msocdn.com",
    "protection.office.com",
    "protection.outlook.com",
    "provisioningapi.microsoftonline.com",
    "public-trust.com",
    "purview.microsoft.com",
    "r.office.microsoft.com",
    "secure.globalsign.com",
    "security.microsoft.com",
    "sharepoint.com",
    "sharepointonline.com",
    "shellprod.msocdn.com",
    "signup.live.com",
    "skype.com",
    "smtp.office365.com",
    "spoprod-a.akamaihd.net",
    "static.microsoft",
    "storage.live.com",
    "streaming.mediaservices.windows.net",
    "support.microsoft.com",
    "svc.ms",
    "sway.com",
    "symcb.com",
    "symcd.com",
    "teams.cloud.microsoft",
    "teams.microsoft.com",
    "technet.microsoft.com",
    "tse1.mm.bing.net",
    "usercontent.microsoft",
    "verisign.com",
    "verisign.net",
    "virtualearth.net",
    "wns.windows.com",
    "wus-www.sway-cdn.com",
    "wus-www.sway-extensions.com",
    "www.acompli.com",
    "www.bing.com",
    "www.digicert.com",
    "www.microsoft.com",
    "www.microsoft365.com",
    "www.onedrive.com",
    "www.outlook.com",
    "www.sway.com",
    "yammer.com",
    "yammerusercontent.com"
  ],
  "matching_attributes": [
    "domain",
    "domain|ip",
    "hostname"
  ],
  "name": "List of known Office 365 URLs",
  "type": "string",
  "version": 20260611
}

=== MISP/misp-warninglists/lists/cloudflare/list.json
{
  "description": "List of known Cloudflare IP ranges (https://www.cloudflare.com/ips/)",
  "list": [
    "103.21.244.0/22",
    "103.22.200.0/22",
    "103.31.4.0/22",
    "104.16.0.0/13",
    "104.24.0.0/14",
    "108.162.192.0/18",
    "131.0.72.0/22",
    "141.101.64.0/18",
    "162.158.0.0/15",
    "172.64.0.0/13",
    "173.245.48.0/20",
    "188.114.96.0/20",
    "190.93.240.0/20",
    "197.234.240.0/22",
    "198.41.128.0/17",
    "2400:cb00::/32",
    "2405:8100::/32",
    "2405:b500::/32",
    "2606:4700::/32",
    "2803:f800::/32",
    "2a06:98c0::/29",
    "2c0f:f248::/32"
  ],
  "matching_attributes": [
    "ip-src",
    "ip-dst",
    "domain|ip",
    "ip-src|port",
    "ip-dst|port"
  ],
  "name": "List of known Cloudflare IP ranges",
  "type": "cidr",
  "version": 20260520
}
