=== MISP/misp-warninglists/schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "title": "Validator for misp-warninglists",
  "id": "https://www.github.com/MISP/misp-warninglists/schema.json",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "description": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "version": {
      "type": "integer"
    },
    "list": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    },
    "type": {
      "type": "string",
      "enum": [
        "string",
        "substring",
        "hostname",
        "cidr",
        "regex"
      ]
    },
    "matching_attributes": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    }
  },
  "required": [
    "list",
    "description",
    "version",
    "name",
    "type"
  ]
}

=== MISP/misp-warninglists/lists/ipinfo-nt-scanning/list.json
{
  "description": "List containing IP's associated with the Ipinfo scanners. This scanner CIDR range is extracted from CIRCL Network Telescope analysis on 2026/06/01",
  "list": [
    "146.185.196.46/32",
    "146.185.199.31/32",
    "146.185.215.117/32",
    "146.185.219.214/32",
    "146.185.248.89/32",
    "185.101.139.61/32",
    "37.9.35.222/32",
    "5.188.133.153/32",
    "5.188.168.53/32",
    "5.188.35.96/32",
    "5.188.4.64/32",
    "5.189.201.217/32",
    "5.189.221.56/32",
    "5.189.223.251/32",
    "89.44.193.185/32",
    "91.243.84.44/32",
    "92.223.73.43/32",
    "92.223.79.236/32",
    "92.38.131.214/32",
    "92.38.132.72/32",
    "92.38.135.237/32",
    "92.38.149.10/32",
    "92.38.171.57/32"
  ],
  "matching_attributes": [
    "ip-src",
    "ip-dst",
    "domain|ip",
    "ip-dst|port",
    "ip-src|port"
  ],
  "name": "Ipinfo IP Ranges Used for Scanning",
  "type": "cidr",
  "version": 26060109
}

=== MISP/misp-warninglists/lists/cypex-nt-scanning/list.json
{
  "description": "List containing IP's associated with the Cypex scanners. This scanner CIDR range is extracted from CIRCL Network Telescope analysis on 2026/03/13",
  "list": [
    "18.117.57.162/32",
    "18.190.163.148/32",
    "18.217.194.148/32",
    "18.221.137.47/32",
    "18.223.104.85/32",
    "3.136.208.236/32",
    "3.136.67.107/32",
    "3.143.152.247/32",
    "3.148.147.222/32",
    "52.14.122.207/32",
    "52.14.58.0/32",
    "52.15.85.154/32"
  ],
  "matching_attributes": [
    "ip-src",
    "ip-dst",
    "domain|ip",
    "ip-dst|port",
    "ip-src|port"
  ],
  "name": "Cypex IP Ranges Used for Scanning",
  "type": "cidr",
  "version": 26031314
}

=== MISP/misp-warninglists/lists/openai-gptbot/list.json
{
  "description": "OpenAI gptbot crawler (https://openai.com/gptbot-ranges.txt)",
  "list": [
    "52.230.152.0/24",
    "52.233.106.0/24"
  ],
  "matching_attributes": [
    "ip-src",
    "ip-dst",
    "domain|ip",
    "ip-src|port",
    "ip-dst|port"
  ],
  "name": "List of known IP address ranges for OpenAI GPT crawler bot",
  "type": "cidr",
  "version": 20240422
}

=== MISP/misp-warninglists/lists/umich-cse-connection-attempts/list.json
{
  "description": "University of Michigan Computer Science and Engineering connection attempts page (https://cse.engin.umich.edu/about/resources/connection-attempts/)",
  "list": [
    "141.212.120.0/24",
    "141.212.121.0/24",
    "141.212.122.0/24",
    "141.212.123.0/24",
    "141.212.124.0/24",
    "141.212.125.0/24"
  ],
  "matching_attributes": [
    "ip-src",
    "ip-dst",
    "domain|ip",
    "ip-src|port",
    "ip-dst|port"
  ],
  "name": "University of Michigan CSE connection-attempt network ranges",
  "type": "cidr",
  "version": 20260528
}

=== MISP/misp-warninglists/lists/whats-my-ip/list.json
{
  "description": "Event contains one or more entries of known 'what's my ip' domains",
  "list": [
    "2ip.ru",
    "2ip.tools",
    "aboutmyip.com",
    "api.ipify.org",
    "api.myip.com",
    "api.wipmania.com",
    "bearsmyip.com",
    "bot.whatismyipaddress.com",
    "check-my-ip.net",
    "checkip-waw.dyndns.com",
    "checkip.amazonaws.com",
    "checkip.dns.he.net",
    "checkip.dyndns.com",
    "checkip.dyndns.es",
    "checkip.dyndns.org",
    "checkip.narak.com",
    "checkmyip.com",
    "cmyip.com",
    "cmyip.net",
    "crymyip.com",
    "curlmyip.com",
    "curlmyip.net",
    "dawhois.com",
    "db-ip.com",
    "dnswatch.info",
    "dpool.sina.com.cn",
    "e-localizaip.com",
    "extreme-ip-lookup.com",
    "findmyip.org",
    "findmyipaddress.com",
    "formyip.com",
    "freegeoip.app",
    "freegeoip.live",
    "geoip.co.uk",
    "geoip.vmn.net",
    "geoiptool.com",
    "get-myip.com",
    "getmyip.org",
    "hostip.info",
    "icanhazip.com",
    "ident.me",
    "ifcfg.me",
    "ifconfig.co",
    "ifconfig.me",
    "ilmioip.it",
    "indirizzo-ip.com",
    "inet-ip.info",
    "ip-1.com",
    "ip-addr.es",
    "ip-address.cc",
    "ip-address.ru",
    "ip-adress.com",
    "ip-adress.eu",
    "ip-api.com",
    "ip-check.info",
    "ip-detect.net",
    "ip-info.ff.avast.com",
    "ip-info.org",
    "ip-info.xyz",
    "ip-ping.ru",
    "ip-score.com",
    "ip-secrets.com",
    "ip-who-is.com",
    "ip-whois.net",
    "ip.amulex.com",
    "ip.anysrc.net",
    "ip.cctv.pk",
    "ip.chinaz.com",
    "ip.cn",
    "ip.my-proxy.com",
    "ip.taobao.com",
    "ip.tool.la",
    "ip.tyk.nu",
    "ip.webmasterhome.cn",
    "ip138.com",
    "ip2location.com",
    "ip2nation.com",
    "ip4.me",
    "ipaddress.com",
    "ipaddress.org",
    "ipaddresscheck.com",
    "ipapi.co",
    "ipchecker.info",
    "ipchicken.com",
    "ipecho.net",
    "ipify.org",
    "ipinfo.info",
    "ipinfo.io",
    "ipinfodb.com",
    "ipleak.net",
    "iplocation.net",
    "iplogger.ru",
    "ipmonkey.com",
    "iptrackeronline.com",
    "ipv4bot.whatismyipaddress.com",
    "ipv6-test.com",
    "ipv6bot.whatismyipaddress.com",
    "keliweb.it",
    "l2.io",
    "localizaip.com.br",
    "meip.eu",
    "meuip.net.br",
    "mio-ip.it",
    "mioip.biz",
    "mioip.ch",
    "mioip.info",
    "mioip.it",
    "mioip.org",
    "mioip.win",
    "mon-ip.com",
    "my-ip-address.net",
    "mycamip.com",
    "myexternalip.com",
    "myglobalip.com",
    "myip.am",
    "myip.by",
    "myip.cc",
    "myip.cf",
    "myip.ch",
    "myip.cn",
    "myip.co.il",
    "myip.co.nz",
    "myip.com.br",
    "myip.com.tw",
    "myip.com.ua",
    "myip.cz",
    "myip.dk",
    "myip.dnsdynamic.org",
    "myip.dnsomatic.com",
    "myip.dramor.net",
    "myip.easylife.tw",
    "myip.es",
    "myip.eu",
    "myip.fi",
    "myip.gr",
    "myip.heltech.se",
    "myip.ht",
    "myip.info",
    "myip.io",
    "myip.is",
    "myip.israel.net",
    "myip.jacware.com",
    "myip.knet.ca",
    "myip.kz",
    "myip.ma",
    "myip.ms",
    "myip.mudfish.net",
    "myip.mysau.com.au",
    "myip.net",
    "myip.nl",
    "myip.nmonitoring.com",
    "myip.northstate.net",
    "myip.nu",
    "myip.opendns.com",
    "myip.ozymo.com",
    "myip.report",
    "myip.rs.sr",
    "myip.ru",
    "myip.sdu.dk",
    "myip.se",
    "myip.shorty.org",
    "myip.surfeasy.com",
    "myip.telespex.com",
    "myip.tk",
    "myip.tw",
    "myip.ua.edu",
    "myip.uconn.edu",
    "myip.v6shell.org",
    "myip.zone",
    "myipaddress.com",
    "myipinfo.net",
    "myipnow.com",
    "myipnumber.com",
    "myiponline.com",
    "mylocation.org",
    "readip.info",
    "sfml-dev.org",
    "shmyip.com",
    "show-ip.com",
    "show-my-ip.de",
    "showip.net",
    "showipinfo.net",
    "showmemyip.com",
    "showmyip.co.uk",
    "showmyip.com",
    "showmyip.com.ar",
    "showmyip.gr",
    "showmyipaddress.com",
    "showmyipaddress.eu",
    "showmyipnow.com",
    "smart-ip.net",
    "tell-my-ip.com",
    "tracemyip.com",
    "tracemyip.org",
    "trackip.net",
    "ultratools.com",
    "utrace.de",
    "v4.ident.me",
    "v6.ident.me",
    "vermiip.es",
    "vinflag.com",
    "whatismybrowser.com",
    "whatismyip.akamai.com",
    "whatismyip.ca",
    "whatismyip.com",
    "whatismyip.com.br",
    "whatismyip.everdot.org",
    "whatismyip.li",
    "whatismyip.net",
    "whatismyip.org",
    "whatismyipaddress.com",
    "whatismypublicip.com",
    "whatmyip.us",
    "whats-my-ip-address.org",
    "whatsmyip.ie",
    "whatsmyip.net",
    "whatsmyip.org",
    "whatsmyip.us",
    "whatsmyipaddress.com",
    "whatsmyipaddress.net",
    "whereisip.net",
    "whoer.net",
    "wtfismyip.com",
    "www.ip.cn",
    "xmyip.com",
    "yougetsignal.com",
    "youip.net",
    "your-ip-address.com",
    "yourip.us"
  ],
  "matching_attributes": [
    "domain",
    "hostname",
    "domain|ip",
    "uri",
    "url"
  ],
  "name": "List of known domains to know external IP",
  "type": "hostname",
  "version": 7
}

=== MISP/misp-warninglists/lists/umbrella-blockpage-v6/list.json
{
  "description": "Cisco Umbrella blockpage in IPv6",
  "list": [
    "::ffff:9270:3d68",
    "::ffff:9270:3d69",
    "::ffff:9270:3d6a",
    "::ffff:9270:3d6b",
    "::ffff:9270:3d6c",
    "::ffff:9270:3d6e"
  ],
  "matching_attributes": [
    "ip-src",
    "ip-dst",
    "domain|ip"
  ],
  "name": "cisco-umbrella-blockpage-ipv6",
  "type": "cidr",
  "version": 20260520
}

=== MISP/misp-warninglists/lists/shadowforce-nt-scanning/list.json
{
  "description": "List containing IP's associated with the Shadowforce scanners. This scanner CIDR range is extracted from CIRCL Network Telescope analysis on 2026/06/01",
  "list": [
    "128.199.44.215/32",
    "142.93.135.160/32",
    "146.190.21.73/32",
    "152.42.136.22/32",
    "159.223.0.20/32",
    "159.223.231.254/32",
    "159.65.193.17/32",
    "159.65.206.235/32",
    "161.35.145.35/32",
    "164.92.148.118/32",
    "164.92.159.100/32",
    "164.92.215.178/32",
    "164.92.219.121/32",
    "165.22.193.223/32",
    "167.172.47.74/32",
    "167.99.211.88/32",
    "178.128.250.218/32",
    "209.38.165.60/32",
    "209.38.96.38/32",
    "68.183.11.224/32",
    "68.183.3.153/32"
  ],
  "matching_attributes": [
    "ip-src",
    "ip-dst",
    "domain|ip",
    "ip-dst|port",
    "ip-src|port"
  ],
  "name": "Shadowforce IP Ranges Used for Scanning",
  "type": "cidr",
  "version": 26060109
}

=== MISP/misp-warninglists/lists/automated-malware-analysis/list.json
{
  "name": "List of known domains used by automated malware analysis services",
  "version": 1,
  "description": "Domains used by automated malware analysis services",
  "type": "substring",
  "matching_attributes": [
    "domain",
    "hostname",
    "domain|ip",
    "url"
  ],
  "list": [
    "virustotal.com",
    "malwr.com",
    "hybrid-analysis.com",
    "emergingthreats.net",
    "joesandbox.com",
    "anlyz.io",
    "detux.org",
    "akana.mobiseclab.org",
    "sandbox.pikker.ee",
    "www.threatexpert.com",
    "www.vicheck.ca"
  ]
}
