=== MISP/misp-warninglists/schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "title": "Validator for misp-warninglists",
  "id": "https://www.github.com/MISP/misp-warninglists/schema.json",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "description": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "version": {
      "type": "integer"
    },
    "list": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    },
    "type": {
      "type": "string",
      "enum": [
        "string",
        "substring",
        "hostname",
        "cidr",
        "regex"
      ]
    },
    "matching_attributes": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    }
  },
  "required": [
    "list",
    "description",
    "version",
    "name",
    "type"
  ]
}

=== MISP/misp-warninglists/lists/microsoft-azure-appid/list.json
{
  "description": "List of Azure Application IDs (https://learn.microsoft.com/en-us/troubleshoot/azure/active-directory/verify-first-party-apps-sign-in)",
  "list": [
    "14d82eec-204b-4c2f-b7e8-296a70dab67e",
    "5572c4c0-d078-44ce-b81c-6cbf8d3ed39e",
    "7ae974c5-1af7-4923-af3a-fb1fd14dcb7e",
    "de8bc8b5-d9f9-48b1-a8ad-b748da725064"
  ],
  "matching_attributes": [
    "azure-application-id"
  ],
  "name": "List of Azure Applicaiton IDs",
  "type": "string",
  "version": 20260520
}

=== MISP/misp-warninglists/lists/onyphe-scanner/list.json
{
  "description": "Onyphe Scanner (https://www.onyphe.io/)",
  "list": [
    "195.184.76.0/24",
    "2001:41d0:33a:a00::400/124",
    "2001:41d0:33d:9200::400/124",
    "2a14:f100::/29",
    "51.254.49.96/28",
    "91.196.152.0/24",
    "91.230.168.0/24",
    "91.231.89.0/24",
    "94.231.206.0/24"
  ],
  "matching_attributes": [
    "ip-src",
    "ip-dst",
    "domain|ip",
    "ip-src|port",
    "ip-dst|port"
  ],
  "name": "List of published IP address ranges for Onyphe Scanner",
  "type": "cidr",
  "version": 20260611
}

=== MISP/misp-warninglists/lists/alphastrike-research-nt-scanning/list.json
{
  "description": "List containing IP's associated with the Alphastrike research scanners. This scanner CIDR range is extracted from CIRCL Network Telescope analysis on 2026/06/01",
  "list": [
    "194.187.176.1/32",
    "194.187.176.128/25",
    "194.187.176.16/28",
    "194.187.176.2/31",
    "194.187.176.32/27",
    "194.187.176.4/30",
    "194.187.176.64/26",
    "194.187.176.8/29",
    "45.83.64.128/25",
    "45.83.64.16/28",
    "45.83.64.2/31",
    "45.83.64.32/27",
    "45.83.64.4/30",
    "45.83.64.64/26",
    "45.83.64.8/29",
    "45.83.65.0/24",
    "45.83.66.0/24",
    "45.83.67.0/25",
    "45.83.67.128/26",
    "45.83.67.192/27",
    "45.83.67.224/28",
    "45.83.67.240/29"
  ],
  "matching_attributes": [
    "ip-src",
    "ip-dst",
    "domain|ip",
    "ip-dst|port",
    "ip-src|port"
  ],
  "name": "Alphastrike research IP Ranges Used for Scanning",
  "type": "cidr",
  "version": 26060109
}

=== MISP/misp-warninglists/lists/internetcleanup-scanner/list.json
{
  "description": "Internet Cleanup Foundation scaninfo (https://internetcleanup.foundation/scaninfo/)",
  "list": [
    "145.220.76.240/32",
    "145.220.91.28/31",
    "185.71.61.126/31",
    "185.71.61.129/32",
    "185.71.61.140/32",
    "37.97.145.112/32"
  ],
  "matching_attributes": [
    "ip-src",
    "ip-dst",
    "domain|ip",
    "ip-src|port",
    "ip-dst|port"
  ],
  "name": "List of published IP address ranges for Internet Cleanup Foundation scanners",
  "type": "cidr",
  "version": 20260528
}

=== MISP/misp-warninglists/lists/research-scanner-nt-scanning/list.json
{
  "description": "List containing IP's associated with the Research scanner scanners. This scanner CIDR range is extracted from CIRCL Network Telescope analysis on 2026/06/01",
  "list": [
    "138.197.101.95/32",
    "138.197.118.33/32",
    "138.68.249.116/32",
    "157.245.176.143/32",
    "157.245.252.5/32",
    "159.223.203.97/32",
    "161.35.230.183/32",
    "161.35.230.3/32",
    "161.35.236.116/32",
    "161.35.236.158/32",
    "161.35.238.241/32",
    "161.35.56.30/32",
    "167.172.148.206/32",
    "167.71.102.181/32",
    "167.71.102.95/32",
    "167.71.110.14/32",
    "167.99.1.98/32",
    "167.99.107.57/32",
    "167.99.119.168/32",
    "178.128.66.109/32",
    "178.128.66.56/32",
    "64.227.106.112/32",
    "64.227.97.195/32",
    "64.227.99.233/32",
    "67.207.95.230/32"
  ],
  "matching_attributes": [
    "ip-src",
    "ip-dst",
    "domain|ip",
    "ip-dst|port",
    "ip-src|port"
  ],
  "name": "Research scanner IP Ranges Used for Scanning",
  "type": "cidr",
  "version": 26060109
}

=== MISP/misp-warninglists/lists/smtp-receiving-ips/list.json
{
  "description": "List of IP addresses for known SMTP servers.",
  "list": [
    "103.129.252.43",
    "103.129.252.44",
    "103.129.252.65",
    "103.168.172.216",
    "103.168.172.217",
    "103.168.172.218",
    "103.168.172.219",
    "103.168.172.220",
    "103.168.172.221",
    "103.168.172.222",
    "103.168.172.223",
    "106.10.248.73",
    "106.10.248.74",
    "106.11.232.89",
    "108.177.125.26",
    "108.177.15.26",
    "108.177.15.27",
    "117.53.116.15",
    "124.83.237.242",
    "124.83.237.243",
    "124.83.237.244",
    "124.83.237.245",
    "124.83.237.246",
    "124.83.237.247",
    "124.83.237.248",
    "124.83.237.249",
    "125.209.222.14",
    "125.209.238.100",
    "125.209.238.137",
    "135.125.7.163",
    "135.125.7.164",
    "14.18.69.193",
    "142.250.147.27",
    "142.251.127.26",
    "142.251.127.27",
    "142.251.168.26",
    "147.135.98.120",
    "15.161.115.94",
    "15.222.199.59",
    "154.18.236.100",
    "154.18.236.98",
    "154.18.236.99",
    "157.255.221.247",
    "157.255.4.241",
    "158.51.79.240",
    "160.92.124.66",
    "162.62.116.184",
    "168.0.133.10",
    "17.42.251.62",
    "17.56.9.31",
    "17.57.152.5",
    "17.57.154.33",
    "17.57.155.25",
    "17.57.156.30",
    "172.253.158.27",
    "173.194.76.26",
    "173.194.76.27",
    "173.252.87.251",
    "176.119.200.128",
    "176.119.200.129",
    "177.153.23.241",
    "177.153.23.242",
    "177.154.139.187",
    "181.30.137.5",
    "183.79.221.216",
    "183.79.221.217",
    "183.79.221.218",
    "183.79.221.219",
    "185.138.56.198",
    "185.138.56.208",
    "185.205.69.211",
    "185.205.69.213",
    "185.205.69.214",
    "185.205.70.128",
    "185.205.70.129",
    "185.3.161.12",
    "185.70.42.128",
    "185.70.42.129",
    "186.202.4.42",
    "186.234.171.11",
    "188.125.72.73",
    "188.125.72.74",
    "192.178.213.27",
    "194.19.134.70",
    "194.19.134.80",
    "194.25.134.72",
    "194.25.134.73",
    "194.25.134.8",
    "194.25.134.9",
    "195.130.132.8",
    "195.130.132.9",
    "195.130.217.201",
    "195.130.217.211",
    "195.130.217.241",
    "195.238.22.25",
    "198.58.121.58",
    "20.157.67.142",
    "200.147.41.201",
    "200.234.204.130",
    "2001:2010:18:1::70",
    "2001:2010:18:1::80",
    "201.7.188.133",
    "202.12.124.216",
    "202.12.124.217",
    "202.12.124.218",
    "202.12.124.219",
    "202.131.24.28",
    "202.131.24.29",
    "202.131.26.30",
    "202.93.77.238",
    "202.93.77.239",
    "202.93.77.240",
    "202.93.77.241",
    "202.93.78.239",
    "202.93.78.240",
    "202.93.78.241",
    "202.93.78.242",
    "203.205.219.57",
    "203.216.254.88",
    "203.216.254.89",
    "203.216.254.90",
    "203.216.254.91",
    "204.141.43.23",
    "204.75.18.216",
    "204.75.18.217",
    "209.71.208.7",
    "211.183.208.52",
    "211.183.211.51",
    "211.249.219.37",
    "211.249.219.43",
    "212.227.15.10",
    "212.227.15.150",
    "212.227.15.154",
    "212.227.15.17",
    "212.227.15.40",
    "212.227.15.9",
    "212.227.17.4",
    "212.227.17.5",
    "212.227.17.8",
    "212.27.42.58",
    "212.27.42.59",
    "212.27.48.6",
    "212.27.48.7",
    "213.165.67.123",
    "213.205.33.244",
    "213.205.33.61",
    "213.205.33.63",
    "213.205.33.64",
    "213.209.1.129",
    "213.209.1.130",
    "216.163.190.10",
    "217.69.139.150",
    "217.72.192.66",
    "223.130.202.36",
    "2404:6800:4003:c26::1b",
    "2404:6800:4008:c01::1b",
    "2408:8756:3af0:3009::126",
    "2408:8756:f50:1::63",
    "2408:8756:f50:200f::12a",
    "240d:c040:1:40::133",
    "240e:938:a07:6:0:14:203:54",
    "240e:938:a07:6:0:14:20:13",
    "240e:97c:2f:1001::14",
    "240e:97c:2f:1001::1b",
    "240e:97c:2f:1003::34",
    "240e:97c:2f::1c",
    "2a00:1450:4001:c21::1a",
    "2a00:1450:4001:c21::1b",
    "2a00:1450:400c:c00::1a",
    "2a00:1450:400c:c00::1b",
    "2a00:1450:400c:c02::1b",
    "2a00:1450:400c:c0b::1a",
    "2a00:1450:400c:c0b::1b",
    "2a00:1450:400c:c0c::1a",
    "2a00:1450:400c:c0c::1b",
    "2a00:1450:4010:c22::1a",
    "2a00:1450:4013:c1e::1a",
    "2a00:1450:4025:c01::1a",
    "2a02:598:2::1042",
    "2a02:598:2::1090",
    "2a02:6b8::311",
    "2a03:2880:11ff:fffd:face:b00c:0:686e",
    "2a07:a80:1::198",
    "2a07:a80:1::208",
    "3.211.210.226",
    "3.96.81.40",
    "34.141.161.132",
    "34.90.152.141",
    "35.152.200.217",
    "36.51.224.198",
    "44.206.9.87",
    "44.210.166.32",
    "46.23.82.244",
    "46.255.225.8",
    "46.255.227.8",
    "47.43.18.9",
    "51.81.232.218",
    "51.81.61.70",
    "51.81.61.71",
    "51.89.43.215",
    "51.89.43.216",
    "52.101.10.11",
    "52.101.10.3",
    "52.101.11.11",
    "52.101.11.18",
    "52.101.11.4",
    "52.101.124.116",
    "52.101.157.0",
    "52.101.40.5",
    "52.101.40.7",
    "52.101.41.2",
    "52.101.41.23",
    "52.101.41.55",
    "52.101.41.57",
    "52.101.42.17",
    "52.101.50.3",
    "52.101.50.9",
    "52.101.68.13",
    "52.101.68.2",
    "52.101.68.24",
    "52.101.68.36",
    "52.101.73.10",
    "52.101.73.152",
    "52.101.73.2",
    "52.101.73.22",
    "52.101.73.30",
    "52.101.9.10",
    "52.101.9.13",
    "52.101.9.18",
    "52.101.9.22",
    "54.164.173.191",
    "54.197.5.236",
    "58.254.165.118",
    "58.254.165.82",
    "64.136.44.37",
    "64.136.52.37",
    "64.233.166.27",
    "64.233.167.27",
    "64.233.184.27",
    "65.20.50.207",
    "67.195.204.72",
    "67.195.204.73",
    "67.195.204.75",
    "67.195.204.77",
    "67.195.204.79",
    "67.195.204.80",
    "67.195.204.82",
    "67.195.228.106",
    "67.195.228.109",
    "67.195.228.111",
    "67.195.228.74",
    "67.195.228.84",
    "67.195.228.86",
    "67.195.228.94",
    "72.51.60.131",
    "72.51.60.132",
    "72.51.60.133",
    "72.51.60.134",
    "74.125.206.26",
    "74.125.206.27",
    "74.125.71.26",
    "74.208.5.20",
    "74.208.5.22",
    "74.6.144.41",
    "77.75.77.42",
    "77.75.77.90",
    "77.88.21.249",
    "80.12.24.83",
    "80.12.26.32",
    "81.19.78.69",
    "84.116.6.18",
    "91.220.42.201",
    "91.220.42.211",
    "91.220.42.241",
    "93.17.128.123",
    "93.17.128.165",
    "94.100.180.31",
    "96.102.157.180",
    "96.102.157.181",
    "96.102.18.146",
    "96.102.18.147",
    "96.103.145.162",
    "96.103.145.163",
    "98.136.96.74",
    "98.136.96.75",
    "98.136.96.76",
    "98.136.96.77",
    "98.136.96.91",
    "98.136.96.92",
    "98.136.96.93",
    "98.137.26.68",
    "98.138.3.192"
  ],
  "matching_attributes": [
    "ip-src",
    "ip-dst",
    "domain|ip",
    "ip-src|port",
    "ip-dst|port"
  ],
  "name": "List of known SMTP receiving IP addresses",
  "type": "cidr",
  "version": 20260611
}

=== MISP/misp-warninglists/lists/findip-host/list.json
{
  "description": "Event contains one or more entries of known hostname querying your source IP.",
  "list": [
    "api.extralargecoffee.com",
    "ip.dyn.bortzmeyer.fr",
    "ip.parrotdns.com",
    "ns.rydgames.com",
    "o-o.myaddr.l.google.com",
    "resolver-identity.cloudfront.net",
    "resolver.00f.net",
    "whoami.akamai.net",
    "whoami.nisl-research.com",
    "whoami.v4.powerdns.org"
  ],
  "matching_attributes": [
    "domain",
    "hostname",
    "domain|ip"
  ],
  "name": "List of known hostname used for querying your source IP. This can be used as exclusion for your Passive DNS lookup.",
  "type": "hostname",
  "version": 3
}

=== MISP/misp-warninglists/lists/fastly/list.json
{
  "description": "Fastly IP address ranges (https://api.fastly.com/public-ip-list)",
  "list": [
    "103.244.50.0/24",
    "103.245.222.0/23",
    "103.245.224.0/24",
    "104.156.80.0/20",
    "146.75.0.0/16",
    "151.101.0.0/16",
    "157.52.64.0/18",
    "167.82.0.0/17",
    "167.82.128.0/20",
    "167.82.160.0/20",
    "167.82.224.0/20",
    "172.111.64.0/18",
    "185.31.16.0/22",
    "199.232.0.0/16",
    "199.27.72.0/21",
    "23.235.32.0/20",
    "2a04:4e40::/32",
    "2a04:4e42::/32",
    "43.249.72.0/22"
  ],
  "matching_attributes": [
    "ip-src",
    "ip-dst",
    "domain|ip"
  ],
  "name": "List of known Fastly IP address ranges",
  "type": "cidr",
  "version": 20201106
}
